services:
  flask-app:
    build: .
    restart: always
    ports:
      - "8080:8080" # Map port 8080 of the container to 8080 of the host
    volumes:
      - ./patterns:/app/patterns # Map host folder to container folder
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    environment:
      - FLASK_ENV=development # Set environment variables for Flask
    container_name: flask-theta-rho-app